version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_hibernate_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: db_hibernate_1
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge